services:
  application:
    build: .
    image: scott1264registry.azurecr.io/springbootdemo:latest
    container_name: scotts-application
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://scotts-database:3306/registrar
      SPRING_DATASOURCE_USERNAME: user123
      SPRING_DATASOURCE_PASSWORD: password123
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: scotts-database
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - MyData:/var/lib/mysql:rw
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      MYSQL_DATABASE: registrar
      MYSQL_USER: user123
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_PASSWORD: password123

volumes:
  MyData: