apiVersion: v1
kind: Service
metadata:
  name: springbootdemo
  labels:
    app: springbootdemo
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: springbootdemo
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdemo
  labels:
    app: springbootdemo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: springbootdemo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: springbootdemo
    spec:
      containers:
      - image: scott1264registry.azurecr.io/springbootdemo:latest
        name: springbootdemo
        imagePullPolicy: IfNotPresent
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql-springbootdemo-smchenry2014-springbootdemo.e.aivencloud.com:20083/registrar
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: springbootdemo-secret
                key: DATABASE_USERNAME
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: springbootdemo-secret
                key: DATABASE_PASSWORD
        ports:
        - containerPort: 8080
          name: springbootdemo